Unitunes/Models/Livro.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unitunes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livro : Media
    {
        public short NumeroPaginas { get; set; }
    }
}

Unitunes/Models/ViewModel/LivroViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Unitunes.Models.ViewModel
{
    public class LivroViewModel : MidiaViewModel
    {
        public Livro midia { get; set; }
    }
}

Unitunes/Controllers/CheckoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Unitunes.Models;
using Unitunes.Models.Servicos;

namespace Unitunes.Controllers
{
    [Authorize]
    public class CheckoutController : Controller
    {
        // GET: Checkout
        public ActionResult Index()
        {
            var errMsg = TempData["ErrorMessage"] as string;

            if(errMsg != null)
                ModelState.AddModelError("error", errMsg);


            var idAcademico = Unitunes.Models.Servicos.Academico.getId();
            var credito = Unitunes.Models.Servicos.Academico.getSaldo(idAcademico);

            ViewBag.credito = credito;

            var listaIds = (List<int>)Checkout.getMedias();
            if (listaIds != null)
            {
                var arrayListaId = listaIds.ToArray();

                var ctx = new dbEntities();

                var medias = ctx.MediaSet;
                //like usando arraylistaid e contains d media iD
                var resultado = from m in medias
                                 
                                 where arrayListaId.Contains(m.Id) && m.Ativo == true
                                 select m;

                return View(resultado);
            }

           

            return View();
        }


        public ActionResult Add(int id)
        {
            Checkout.addMedia(id);
            return Redirect("/Checkout");
        }

        public ActionResult Remove(int id)
        {
            Checkout.removeMedia(id);
            return Redirect("/Checkout");
        }



        // GET: Checkout

        [HttpPost]
        public ActionResult Finalizar(double total)
        {
            if (Checkout.getMedias().Count == 0)
            {
                return Redirect("/Checkout");
            }

            var listaIds = (List<int>)Checkout.getMedias();
            if (listaIds != null)
            {
                var arrayListaId = listaIds.ToArray();

                var ctx = new dbEntities();

                var medias = ctx.MediaSet;

                //like usando arraylistaid e contains d media iD
                var listaMedias = from m in medias

                                where arrayListaId.Contains(m.Id) && m.Ativo == true
                                select m;


                //verifica creditos
                var idAcademico = Unitunes.Models.Servicos.Academico.getId();
                var credito = Unitunes.Models.Servicos.Academico.getSaldo(idAcademico);

                if (credito > total)
                {
                   
                    var novoCredito = credito - total;
                    Unitunes.Models.Servicos.Academico.setSaldo(idAcademico,novoCredito);
                    
                    //add 15% ao admin total
                    var novoCreditoAdmin = Unitunes.Models.Servicos.Academico.getSaldo(1)+((total * 15) / 100);
                    Unitunes.Models.Servicos.Academico.setSaldo(1, novoCreditoAdmin);

                    ViewBag.credito = novoCredito;
                   
                    
                    var academicos = ctx.AcademicoSet;
                    // pega obj para referencia a nova transacao
                    var academicoObj = academicos.Find(idAcademico);



                    var transacao = ctx.TransacaoSet;
                    //cria nova transacao para inserir
                    var novaTransacao = new Transacao { AcademicoDaTransacao = academicoObj, Ativo = true, MediasTransacao = listaMedias.ToList(), Valor = total };
                    //cria transacao
                    transacao.Add(novaTransacao);
                    ctx.SaveChanges();
                    //da 15% pro admin e o resto pro autor

                    Checkout.clearCheckout();
                }
                else
                {
                    TempData["ErrorMessage"] = "Credito insuficiente";
                    
                    return Redirect("/Checkout");
                }


                return View(listaMedias);
            }
            return View();
        }

    }
}

Unitunes/Controllers/LoginController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Unitunes.Models;
using Unitunes.Models.ViewModel;
using Unitunes.Models.Servicos;

namespace Unitunes.Controllers
{
    public class LoginController : Controller
    {


        // GET: Login
        public ActionResult Login()
        {
         
               
            
            return View();
        }

        // POST: Login
        [HttpPost]
        public ActionResult Login(string login,string password)
        {

            Unitunes.Models.Academico novoLogin = new Unitunes.Models.Academico();
            novoLogin.Email = login;
            novoLogin.Password = password;

            if (Unitunes.Models.Servicos.Academico.isAcademicoExists(novoLogin))
            {
                Unitunes.Models.Servicos.Academico.autenticar(novoLogin);
                return Redirect("/Login/Principal");

            }
            else
            {
                ModelState.AddModelError("error", "Usuario não existe");
            }

            return View();

        }

        //GET : REGISTAR
        public ActionResult Registrar()
        {
       
            return View();
        }

        //POST : REGISTRAR
        [HttpPost]
        public ActionResult Registrar(Unitunes.Models.Academico academico)
        {
            
            //verifica se existe o registro
            //quando enviar o post

            if (ModelState.IsValid)
            {

                var ctx = new dbEntities();

                var academicos = ctx.AcademicoSet;


                //verifica se usuario nao existe
                if (!Unitunes.Models.Servicos.Academico.isAcademicoExists(academico))
                {

                    //cria usuario
                    Unitunes.Models.Servicos.Academico.adicionarAcademico(academico);
                    Unitunes.Models.Servicos.Academico.autenticar(academico);
                    return Redirect("/Login/Principal");

                }
                else
                {
                    ModelState.AddModelError("error", "Usuario Já existe");
                }
            }
            else
            {
                ModelState.AddModelError("error", "Preencha o formulario corretamente");
            }
                // The action is a POST.
            return View();
        }


        //necessita login
        [Authorize]
        public ActionResult Logout()
        {
            Unitunes.Models.Servicos.Academico.logoff();
            return Redirect("/Login/Login");
        }

        //necessita loginUnitunes.Models
        [Authorize]
        public ActionResult Principal()
        {

            var idAcademico = Unitunes.Models.Servicos.Academico.getId();
            var credito = Unitunes.Models.Servicos.Academico.getSaldo(idAcademico);

            ViewBag.nome = Unitunes.Models.Servicos.Academico.getIdNome();

            ViewBag.credito = credito;
            ViewBag.nome = Unitunes.Models.Servicos.Academico.getIdNome();
            //passa o model pelo view

            //listar tipos
            // nome
            //

            var resultado = (IEnumerable<PrincipalViewModel>)null;
            return View(resultado);
        }

        [Authorize]
        [HttpPost]    
        public ActionResult Principal(string tipo,string nome)
        {
            var idAcademico = Unitunes.Models.Servicos.Academico.getId();
            var credito = Unitunes.Models.Servicos.Academico.getSaldo(idAcademico);

            ViewBag.nome = Unitunes.Models.Servicos.Academico.getIdNome();
            ViewBag.credito = credito;
         

            ViewBag.nome = Unitunes.Models.Servicos.Academico.getIdNome();
            var ctx = new dbEntities();

            var medias = ctx.MediaSet;
            var academico = ctx.AcademicoSet;
            var resultado = (IEnumerable<PrincipalViewModel>)null;

            switch (tipo)
            {
                case "Musica":
                    resultado =     (from m in medias
                                    join a in academico on m.AcademicoId equals a.Id
                                    where m.Nome.Contains(nome) && m.Ativo == true && m is Musica
                                     select new PrincipalViewModel { midia = m, academico = (Unitunes.Models.Academico)a }).AsEnumerable();

                    break;
                case "Video":
                    resultado = (from m in medias
                                    join a in academico on m.AcademicoId equals a.Id
                                    where m.Nome.Contains(nome) && m.Ativo == true && m is Video
                                 select new PrincipalViewModel { midia = m, academico = (Unitunes.Models.Academico)a }).AsEnumerable();
                    break;
                case "Podcast":
                    resultado = (from m in medias
                                join a in academico on m.AcademicoId equals a.Id
                                where m.Nome.Contains(nome) && m.Ativo == true && m is Podcast
                                 select new PrincipalViewModel { midia = m, academico = (Unitunes.Models.Academico)a }).AsEnumerable();
                    break;
                case "Livro":
                    resultado = (from m in medias
                                join a in academico on m.AcademicoId equals a.Id
                                where m.Nome.Contains(nome) && m.Ativo == true && m is Livro
                                select new PrincipalViewModel { midia = m, academico = (Unitunes.Models.Academico)a }).AsEnumerable();
                    break;
            }

            return View(resultado);

            
        }
 
    }
}

Unitunes/Controllers/Midia/LivroController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Unitunes.Models;
using Unitunes.Models.Abstratos;

namespace Unitunes.Controllers.Midia
{
    public class LivroController : Controller
    {
        private dbEntities db = new dbEntities();


        // GET: Videos/Create
        public ActionResult Criar()
        {
            return View();
        }

        // POST: Videos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Criar(Unitunes.Models.ViewModel.LivroViewModel livroViewModel)
        {
            if (ModelState.IsValid)
            {
                if (livroViewModel.arquivoUpload != null)
                {
                    if (livroViewModel.arquivoUpload.ContentLength > 0)
                    {

                        var fileName = Path.GetFileName(livroViewModel.arquivoUpload.FileName);
                        var path = Path.Combine(Server.MapPath("~/App_Data/midias"), fileName);
                        //salva no servidor
                        livroViewModel.arquivoUpload.SaveAs(path);

                        livroViewModel.midia.Caminho = path;
                        //relaciona o id do acadamico na sessao e relaciona na media

                    }

                }

                livroViewModel.midia.AcademicoId = Unitunes.Models.Servicos.Academico.getId();
                livroViewModel.midia.Ativo = true;

                var midiaRepo = Singleton<Unitunes.Models.Repositorios.Midia>.Instance();
                midiaRepo.Save(livroViewModel.midia);

                return Redirect("/Midia/Listar");
            }

            return View(livroViewModel);
        }

        // GET: Videos/Edit/5
        public ActionResult Editar(int id)
        {
            Unitunes.Models.ViewModel.LivroViewModel livroViewModel = new Models.ViewModel.LivroViewModel();

            var midiaRepo = Singleton<Unitunes.Models.Repositorios.Midia>.Instance();

            livroViewModel.midia = (Livro)midiaRepo.GetById(id);


            return View(livroViewModel);
        }

        // POST: Videos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(Unitunes.Models.ViewModel.LivroViewModel livroViewModel)
        {
            var midiaRepo = Singleton<Unitunes.Models.Repositorios.Midia>.Instance();

            if (ModelState.IsValid)
            {
                if (livroViewModel.arquivoUpload != null)
                {
                    if (livroViewModel.arquivoUpload.ContentLength > 0)
                    {

                        var fileName = Path.GetFileName(livroViewModel.arquivoUpload.FileName);
                        var path = Path.Combine(Server.MapPath("~/App_Data/midias"), fileName);
                        //salva no servidor
                        livroViewModel.arquivoUpload.SaveAs(path);


                        livroViewModel.midia.Caminho = path;

                    }
                }

                //nao esquecer academicoID
                livroViewModel.midia.Ativo = true;
                livroViewModel.midia.AcademicoId = Unitunes.Models.Servicos.Academico.getId();
                midiaRepo.Update(livroViewModel.midia);

                return Redirect("/Midia/Listar");
            }
            return View(livroViewModel);


 
        }
        // GET: Videos/Delete/5
        public ActionResult Visualizar(int id)
        {
            Unitunes.Models.ViewModel.LivroViewModel livroViewModel = new Models.ViewModel.LivroViewModel();

            var midiaRepo = Singleton<Unitunes.Models.Repositorios.Midia>.Instance();

            livroViewModel.midia = (Livro)midiaRepo.GetById(id);

            ViewBag.id = livroViewModel.midia.Id;

            return View(livroViewModel);

        }

        // GET: Videos/Delete/5
        public ActionResult Deletar(int id)
        {
            Unitunes.Models.ViewModel.LivroViewModel livroViewModel = new Models.ViewModel.LivroViewModel();

            var midiaRepo = Singleton<Unitunes.Models.Repositorios.Midia>.Instance();

            livroViewModel.midia = (Livro)midiaRepo.GetById(id);


            return View(livroViewModel);

        }

        // POST: Videos/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Deletar(Unitunes.Models.ViewModel.LivroViewModel livroViewModel)
        {
            var midiaRepo = Singleton<Unitunes.Models.Repositorios.Midia>.Instance();
            livroViewModel.midia.Ativo = false;

            midiaRepo.Update(livroViewModel.midia);
            return Redirect("/Midia/Listar");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Unitunes/Views/Livro/Criar.cshtml
@model Unitunes.Models.ViewModel.LivroViewModel
@{
    ViewBag.Title = "Criar ";

}



<h2>Criar</h2>

@using (Html.BeginForm("Criar", "Livro", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Media</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(Model => Model.midia.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(Model => Model.midia.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(Model => Model.midia.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(Model => Model.midia.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(Model => Model.midia.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(Model => Model.midia.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(Model => Model.midia.Publicado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(Model => Model.midia.Publicado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(Model => Model.midia.Publicado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(Model => Model.midia.Preco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(Model => Model.midia.Preco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(Model => Model.midia.Preco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(Model => Model.midia.Categoria, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(Model => Model.midia.Categoria, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(Model => Model.midia.Categoria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(Model => Model.midia.DataCriacao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(Model => Model.midia.DataCriacao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(Model => Model.midia.DataCriacao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Arquivo de Upload", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                <input type="file" name="arquivoUpload" />
                @Html.ValidationMessageFor(Model => Model.arquivoUpload, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.midia.NumeroPaginas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.midia.NumeroPaginas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.midia.NumeroPaginas, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Criar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Principal", "Principal", "Login")
</div>

Unitunes/Views/Livro/Deletar.cshtml
@model Unitunes.Models.ViewModel.LivroViewModel

@{
    ViewBag.Title = "Deletar ";

}



<h2>Criar</h2>

@using (Html.BeginForm("Deletar", "Livro", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Media</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(Model => Model.midia.Id)
        @Html.HiddenFor(Model => Model.midia.AcademicoId)

        <div class="form-group">
            @Html.LabelFor(Model => Model.midia.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(Model => Model.midia.Nome, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(Model => Model.midia.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(Model => Model.midia.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(Model => Model.midia.Descricao, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(Model => Model.midia.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(Model => Model.midia.Publicado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(Model => Model.midia.Publicado, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(Model => Model.midia.Publicado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(Model => Model.midia.Preco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(Model => Model.midia.Preco, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(Model => Model.midia.Preco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(Model => Model.midia.Categoria, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(Model => Model.midia.Categoria, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(Model => Model.midia.Categoria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(Model => Model.midia.DataCriacao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(Model => Model.midia.DataCriacao, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(Model => Model.midia.DataCriacao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Arquivo de Upload", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                <input type="file" name="arquivoUpload" disabled />
                @Html.ValidationMessageFor(Model => Model.arquivoUpload, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.midia.NumeroPaginas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.midia.NumeroPaginas, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.midia.NumeroPaginas, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Deletar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Principal", "Principal", "Login")
</div>

Unitunes/Views/Livro/Visualizar.cshtml
@model Unitunes.Models.ViewModel.LivroViewModel

@{
    ViewBag.Title = "Visualizar ";

}



<h2>Livro</h2>

@using (Html.BeginForm("Deletar", "Livro", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Livro</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(Model => Model.midia.Id)
        @Html.HiddenFor(Model => Model.midia.AcademicoId)

        <div class="form-group">
            @Html.LabelFor(Model => Model.midia.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(Model => Model.midia.Nome, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(Model => Model.midia.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(Model => Model.midia.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(Model => Model.midia.Descricao, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(Model => Model.midia.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(Model => Model.midia.Publicado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(Model => Model.midia.Publicado, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(Model => Model.midia.Publicado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(Model => Model.midia.Preco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(Model => Model.midia.Preco, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(Model => Model.midia.Preco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(Model => Model.midia.Categoria, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(Model => Model.midia.Categoria, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(Model => Model.midia.Categoria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(Model => Model.midia.DataCriacao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(Model => Model.midia.DataCriacao, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(Model => Model.midia.DataCriacao, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.midia.NumeroPaginas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.midia.NumeroPaginas, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.midia.NumeroPaginas, "", new { @class = "text-danger" })
            </div>
        </div>


        
    </div>
}

<div>
   @Html.ActionLink("Adicionar a Pedido", "Add", "Checkout", new { id = ViewBag.id }, null)
    @Html.ActionLink(" Principal", "Principal", "Login")
</div>