Unitunes/Models/ViewModel/PrincipalViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Unitunes.Models.ViewModel
{
    public class PrincipalViewModel : MidiaViewModel
    {
        public Media midia { get; set; }
        public Academico academico { get; set; }
    }
}

Unitunes/Controllers/LoginController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Unitunes.Models;
using Unitunes.Models.ViewModel;
using Unitunes.Models.Servicos;

namespace Unitunes.Controllers
{
    public class LoginController : Controller
    {


        // GET: Login
        public ActionResult Login()
        {
         
               
            
            return View();
        }

        // POST: Login
        [HttpPost]
        public ActionResult Login(string login,string password)
        {

            Unitunes.Models.Academico novoLogin = new Unitunes.Models.Academico();
            novoLogin.Email = login;
            novoLogin.Password = password;

            if (Unitunes.Models.Servicos.Academico.isAcademicoExists(novoLogin))
            {
                Unitunes.Models.Servicos.Academico.autenticar(novoLogin);
                return Redirect("/Login/Principal");

            }
            else
            {
                ModelState.AddModelError("error", "Usuario não existe");
            }

            return View();

        }

        //GET : REGISTAR
        public ActionResult Registrar()
        {
       
            return View();
        }

        //POST : REGISTRAR
        [HttpPost]
        public ActionResult Registrar(Unitunes.Models.Academico academico)
        {
            
            //verifica se existe o registro
            //quando enviar o post

            if (ModelState.IsValid)
            {

                var ctx = new dbEntities();

                var academicos = ctx.AcademicoSet;


                //verifica se usuario nao existe
                if (!Unitunes.Models.Servicos.Academico.isAcademicoExists(academico))
                {

                    //cria usuario
                    Unitunes.Models.Servicos.Academico.adicionarAcademico(academico);
                    Unitunes.Models.Servicos.Academico.autenticar(academico);
                    return Redirect("/Login/Principal");

                }
                else
                {
                    ModelState.AddModelError("error", "Usuario Já existe");
                }
            }
            else
            {
                ModelState.AddModelError("error", "Preencha o formulario corretamente");
            }
                // The action is a POST.
            return View();
        }


        //necessita login
        [Authorize]
        public ActionResult Logout()
        {
            Unitunes.Models.Servicos.Academico.logoff();
            return Redirect("/Login/Login");
        }

        //necessita loginUnitunes.Models
        [Authorize]
        public ActionResult Principal()
        {

            var idAcademico = Unitunes.Models.Servicos.Academico.getId();
            var credito = Unitunes.Models.Servicos.Academico.getSaldo(idAcademico);

            ViewBag.nome = Unitunes.Models.Servicos.Academico.getIdNome();

            ViewBag.credito = credito;
            ViewBag.nome = Unitunes.Models.Servicos.Academico.getIdNome();
            //passa o model pelo view

            //listar tipos
            // nome
            //

            var resultado = (IEnumerable<PrincipalViewModel>)null;
            return View(resultado);
        }

        [Authorize]
        [HttpPost]    
        public ActionResult Principal(string tipo,string nome)
        {
            var idAcademico = Unitunes.Models.Servicos.Academico.getId();
            var credito = Unitunes.Models.Servicos.Academico.getSaldo(idAcademico);

            ViewBag.nome = Unitunes.Models.Servicos.Academico.getIdNome();
            ViewBag.credito = credito;
         

            ViewBag.nome = Unitunes.Models.Servicos.Academico.getIdNome();
            var ctx = new dbEntities();

            var medias = ctx.MediaSet;
            var academico = ctx.AcademicoSet;
            var resultado = (IEnumerable<PrincipalViewModel>)null;

            switch (tipo)
            {
                case "Musica":
                    resultado =     (from m in medias
                                    join a in academico on m.AcademicoId equals a.Id
                                    where m.Nome.Contains(nome) && m.Ativo == true && m is Musica
                                     select new PrincipalViewModel { midia = m, academico = (Unitunes.Models.Academico)a }).AsEnumerable();

                    break;
                case "Video":
                    resultado = (from m in medias
                                    join a in academico on m.AcademicoId equals a.Id
                                    where m.Nome.Contains(nome) && m.Ativo == true && m is Video
                                 select new PrincipalViewModel { midia = m, academico = (Unitunes.Models.Academico)a }).AsEnumerable();
                    break;
                case "Podcast":
                    resultado = (from m in medias
                                join a in academico on m.AcademicoId equals a.Id
                                where m.Nome.Contains(nome) && m.Ativo == true && m is Podcast
                                 select new PrincipalViewModel { midia = m, academico = (Unitunes.Models.Academico)a }).AsEnumerable();
                    break;
                case "Livro":
                    resultado = (from m in medias
                                join a in academico on m.AcademicoId equals a.Id
                                where m.Nome.Contains(nome) && m.Ativo == true && m is Livro
                                select new PrincipalViewModel { midia = m, academico = (Unitunes.Models.Academico)a }).AsEnumerable();
                    break;
            }

            return View(resultado);

            
        }
 
    }
}

Unitunes/Controllers/MidiaController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Unitunes.Models;
using Unitunes.Models.Abstratos;
using Unitunes.Models.Servicos;
using Unitunes.Models.ViewModel;

namespace Unitunes.Controllers
{
    [Authorize]
    public class MidiaController : Controller
    {
        

        //GET : LISTAR MIDIAS
        public ActionResult Listar()
        {
            var midiaRepo = Singleton<Unitunes.Models.Repositorios.Midia>.Instance();
            //passa o model pelo view
            int id = Unitunes.Models.Servicos.Academico.getId();

            var minhasMidias = midiaRepo.GetByIdAcademico(id);


            return View(minhasMidias);
        }

        //GET : LISTAR MIDIAS
        public ActionResult CriarNovaMidia()
        {

            
            return View();
        }

        //GET : LISTAR MIDIAS
        [HttpPost]
        public ActionResult CriarNovaMidia(int opt)
        {
            if (opt == 0)
            {
                
                return Redirect("/Video/Criar");
            }

            if (opt == 1)
            {

                return Redirect("/Livro/Criar");
            }

            if (opt == 2)
            {

                return Redirect("/Musica/Criar");
            }

            if (opt == 3)
            {

                return Redirect("/Podcast/Criar");
            }

            return View();
        }
   }
        
        
 }

Unitunes/Controllers/TransacaoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Unitunes.Models;

namespace Unitunes.Controllers
{
    [Authorize]
    public class TransacaoController : Controller
    {
        private dbEntities db = new dbEntities();


        // GET: Transacao fileResult
        public FileResult Download(int idTransacao, int idMedia)
        {


            var idAcademico = Unitunes.Models.Servicos.Academico.getId();
            var academicos = db.AcademicoSet;
            // pega obj para referencia a nova transacao
            var academicoObj = academicos.Find(idAcademico);
            var resultado = (Transacao)null;
            var caminho = (Media)null;
            
            if (!User.IsInRole("Administrador"))
            {
                resultado = db.TransacaoSet.Where(t => t.AcademicoDaTransacao.Id == idAcademico).First();
                if (resultado != null)
                {
                    try
                    {
                         caminho = resultado.MediasTransacao.Where(m => m.Id == idMedia).First();

                        byte[] fileBytes = System.IO.File.ReadAllBytes(@caminho.Caminho);
                        string fileName = Path.GetFileNameWithoutExtension(@caminho.Caminho);
                        return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
                    }
                    catch (Exception)
                    {
                        return null;
                    }
                }
            }
            else
            {
                try
                {
                    resultado = db.TransacaoSet.Where(t => t.Id == idTransacao).First();
                    caminho = resultado.MediasTransacao.Where(m => m.Id == idMedia).First();

                    byte[] fileBytes = System.IO.File.ReadAllBytes(@caminho.Caminho);
                    string fileName = Path.GetFileNameWithoutExtension(@caminho.Caminho);
                    return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
                }
                catch (Exception)
                {
                    return null;
                }
            }

            return null;
        }

        // GET: Transacao
        public ActionResult Index()
        {
            

            var idAcademico = Unitunes.Models.Servicos.Academico.getId();
            var academicos = db.AcademicoSet;
            // pega obj para referencia a nova transacao
            var academicoObj = academicos.Find(idAcademico);
            
            if (!User.IsInRole("Administrador")) { 
                return View(db.TransacaoSet.Where(t => t.AcademicoDaTransacao.Id == idAcademico).ToList());
            }
            else
            {
                return View(db.TransacaoSet.ToList());
            }
        }

        // GET: Transacao/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Transacao transacao = db.TransacaoSet.Find(id);
            if (transacao == null)
            {
                return HttpNotFound();
            }
            return View(transacao);
        }



        // Adiciona credito / apenas admin
        [Authorize(Roles="Administrador")]
        public ActionResult AdicionaCredito(int? id)
        {
            var academicos = db.AcademicoSet;
            // pega obj para referencia a nova transacao
            ViewBag.academicos = academicos.ToList();
            return View();
        }

        // Adiciona credito / apenas admin
        [Authorize(Roles = "Administrador")]
        [HttpPost]
        public ActionResult AdicionaCredito(double credito,int academico)
        {
            try { 
                var contas = db.ContaAcademicoSet;

                var conta = contas.Find(academico);
                conta.Credito = credito;

                db.Entry(conta).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
            catch (Exception)
            {

            }
            return Redirect("/Login/Principal");
        }

        

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Unitunes/Views/Login/Login.cshtml
@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>
<form action="/Login/Login" method="POST">

    Login:<input type="text" name="login" style="margin-left:28px" /><br/>
    Password:<input type="password" name="password" /><br /><br />
    <input type="submit" name="Submit" value="Login!" />

</form>

@if (!ViewData.ModelState.IsValid)
{
    @Html.Raw(@Html.ValidationMessage("error"))
}
<br/>
@Html.ActionLink("Registrar", "Login", "Registrar")

Unitunes/Views/Login/Principal.cshtml
@model IEnumerable<Unitunes.Models.ViewModel.PrincipalViewModel>

@{
    ViewBag.Title = "Listar";
}

<h2>Listar</h2>

<p>
    @Html.ActionLink(" Adicionar Nova midia", "CriarNovaMidia", "Midia")|
    @Html.ActionLink(" Minhas midias", "Listar", "Midia")|
    @Html.ActionLink("Checkout", "Index", "Checkout")|
    @Html.ActionLink("Transações", "Index", "Transacao")|
    @Html.ActionLink(" Principal", "Principal", "Login")|
    @Html.ActionLink(" Logout", "Logout", "Login")|
    Creditos: @ViewBag.credito|

    Nome: @ViewBag.nome
    
    @if (User.IsInRole("Administrador"))
    {
         @Html.ActionLink("| Adicionar Creditos", "AdicionaCredito", "Transacao")
    }

</p>


@using (Html.BeginForm("Principal", "Login", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Media</h4>
        <hr />
        <div class="form-group">

            
            <div class="col-md-offset-2 col-md-10">
                
                @{
                    List<SelectListItem> listItems = new List<SelectListItem>();
                    listItems.Add(new SelectListItem
                         {
                             Text = "Livro",
                             Value = "Livro"
                         });
                    listItems.Add(new SelectListItem
                         {
                             Text = "Muscica",
                             Value = "Musica",
                             Selected = true
                         });
                    listItems.Add(new SelectListItem
                         {
                             Text = "Podcast",
                             Value = "Podcast"
                         });
                    listItems.Add(new SelectListItem
                    {
                        Text = "Video",
                        Value = "Video"
                    });
                }

                @Html.DropDownList("tipo", listItems, "-- Selecione --")
                <input type="text" name="nome" />
                <input type="submit" value="Buscar" class="btn btn-default" />
            </div>
        </div>
    </div>

}


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.midia.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.midia.Descricao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.midia.Publicado)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.midia.Preco)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.midia.Categoria)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.midia.DataCriacao)
        </th>

        <th>
            @Html.DisplayName("Tipo")
        </th>
        <th>
           Autor
        </th>
        <th></th>
    </tr>
    @if (Model != null)
    {
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.midia.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.midia.Descricao)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.midia.Publicado)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.midia.Preco)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.midia.Categoria)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.midia.DataCriacao)
                </td>

                <td>
                    @item.midia.GetType().Name
                </td>
                <td>
                    @item.academico.PrimeiroNome
                </td>

                <td>
                    @Html.ActionLink("Visualizar", "Visualizar" , item.midia.GetType().Name, new { id = item.midia.Id }, null) 
                    @Html.ActionLink("Adicionar", "Add", "Checkout", new { id = item.midia.Id }, null)
                    
                </td>
            </tr>
        }
    }
</table>

Unitunes/Views/Login/Registrar.cshtml
@model Unitunes.Models.Academico

@{
    ViewBag.Title = "Registrar";
}

<h2>Registrar</h2>

 <!-- @Html.ValidationSummary("error") -->





@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

   

    <div class="form-horizontal">
        <h4>Academico</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.Password, new { htmlAttributes = new { @class = "form-control control-label col-md-2", placeholder = "Password" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PrimeiroNome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PrimeiroNome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PrimeiroNome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SegundoNome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SegundoNome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SegundoNome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Registrar" class="btn btn-default" />
            </div>
        </div>
    </div>
}
@Html.ActionLink("Login", "Login", "Login")